"""Record readings of the real listing sheets for the front end's demo (writes web/data/sheets.js).

Usage (from server/):
  python -m commands.record_sheets            real OCR; fields mapped from the ground truth (no Gemini call)
  python -m commands.record_sheets --gemini   real OCR and Gemini mapping (billed), scored against the ground truth

The sheets and their ground truth are listed in tests/fixtures/sheets.json. When a sheet's original is
present in assets/, its published copy in web/static/sheets/ is rebuilt first: downscaled the way the
browser does before upload, with contact details masked. OCR runs on that copy, so evidence boxes line
up with the image the site shows, and every value goes through the same evidence checks as a live
extraction. The site keeps both what the pipeline read (`reading`) and the checked values (`confirmed`).
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from PIL import Image, ImageDraw

from apps.listing.checks import detect_checks, fold
from apps.listing.evidence import build_costs, build_fields, canon, contract_lines
from apps.listing.models import FIELD_KEYS, ImageSize, MapperOutput, to_contract
from apps.listing.services import map_fields
from config import OCR_ENGINE_LABEL, load_settings
from extensions import ext_gemini
from extensions.ext_ocr import OcrLine, OcrPage, build_converter, read_page

ROOT = Path(__file__).resolve().parents[2]
SHEETS = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "sheets.json"
OUTPUT = ROOT / "web" / "data" / "sheets.js"
WEB_MAX_EDGE = 2560  # web/config.js MAX_IMAGE_EDGE: the size the browser uploads
MASK_COLOR = (214, 214, 214)
HEADER = """// Generated by `python -m commands.record_sheets` (server/). Do not edit by hand.
// Real listing sheets (images in static/sheets/) and what the extraction pipeline read from them.
// reading:   the pipeline's result. OCR always ran for real; meta.model names the Gemini model that
//            mapped the lines to fields, or is null when they were mapped from the ground truth by hand.
// confirmed: each value checked against the original sheet (server/tests/fixtures/sheets.json).
"""


def build_copy(sheet: dict[str, Any]) -> None:
    source = ROOT / sheet["source"]
    if not source.exists():
        return  # the published copy is kept as is
    target = ROOT / sheet["image"]
    target.parent.mkdir(parents=True, exist_ok=True)
    image = Image.open(source)
    scale = min(1, WEB_MAX_EDGE / max(image.size))
    if image.format == "JPEG" and scale == 1 and not sheet["mask"]:
        # Re-encoding costs OCR accuracy on small print (賃料 was read as 货料), so copy the bytes.
        target.write_bytes(source.read_bytes())
        return
    image = image.convert("RGB")
    if scale < 1:
        image = image.resize((round(image.width * scale), round(image.height * scale)), Image.Resampling.LANCZOS)
    draw = ImageDraw.Draw(image)
    for box in sheet["mask"]:
        draw.rectangle(box, fill=MASK_COLOR)
    # Full-resolution colour (4:4:4): default chroma subsampling blurs red print, and sheets print
    # their caveats in red (「補足事項あり」 became unreadable at 4:2:0, even at quality 100).
    image.save(target, "JPEG", quality=94, subsampling=0, optimize=True, progressive=True)


def _centre(line: OcrLine) -> tuple[float, float]:
    return (line.box[0] + line.box[2]) / 2, (line.box[1] + line.box[3]) / 2


def resolve_lines(page: OcrPage, quotes: list[str], where: str) -> list[int]:
    """Turn quoted text into OCR line ids: an equal line first, otherwise the lines containing it. When a
    quote (say 「16,500円」) is on several lines, take the one nearest the value's other quotes."""
    resolved: list[OcrLine] = []
    for quote in quotes:
        want = fold(quote)  # quotes are written as printed; OCR look-alikes (键交换 for 鍵交換) are folded
        found = [line for line in page.lines if fold(line.text) == want] or [line for line in page.lines if want in fold(line.text)]
        if len(found) > 1 and resolved:
            anchors = [_centre(line) for line in resolved]
            nearest = lambda line: min(abs(_centre(line)[1] - y) + 0.1 * abs(_centre(line)[0] - x) for x, y in anchors)  # noqa: E731
            found = [min(found, key=nearest)]
        if len(found) != 1:
            raise SystemExit(f"{where}: {quote!r} matched {len(found)} OCR lines; quote more of the line in {SHEETS.name}")
        resolved.append(found[0])
    return [line.id for line in resolved]


def truth_mapping(sheet: dict[str, Any], page: OcrPage) -> MapperOutput:
    fields = {key: {"value": spec["value"], "lines": resolve_lines(page, spec["lines"], f"{sheet['id']}.{key}")} for key, spec in sheet["fields"].items()}
    costs = [{**cost, "lines": resolve_lines(page, cost["lines"], f"{sheet['id']}.costs.{cost['label']}")} for cost in sheet.get("costs", [])]
    return MapperOutput.model_validate({"fields": fields, "costs": costs, "warnings": sheet["warnings"]})


def same(got: Any, want: Any) -> bool:
    return canon(got) == canon(want) if isinstance(got, str) and isinstance(want, str) else got == want


def score(sheet: dict[str, Any], fields: dict[str, dict[str, Any]], costs: list[dict[str, Any]]) -> int:
    """Print each field and money term against the ground truth; return the number of mismatches."""
    misses = 0
    for key in FIELD_KEYS:
        got, want = fields[key]["value"], sheet["fields"][key]["value"]
        ok = same(got, want)
        misses += not ok
        print(f"  {'PASS' if ok else 'FAIL'} {key:<16} got={got!r} want={want!r} confidence={fields[key]['confidence']}")
    for want in sheet.get("costs", []):
        key = (want["kind"], want["unit"], want["timing"], want["amount"])
        ok = any((cost["kind"], cost["unit"], cost["timing"], cost["amount"]) == key for cost in costs)
        misses += not ok
        print(f"  {'PASS' if ok else 'FAIL'} cost {want['label']}: {want['amount']} {want['unit']} ({want['timing']})")
    return misses


async def record(use_gemini: bool) -> int:
    settings = load_settings()
    if use_gemini and not settings.gemini_api_key:
        print("GEMINI_API_KEY is not set (server/.env).")
        return 1
    app = SimpleNamespace(state=SimpleNamespace(settings=settings))
    ext_gemini.init_app(app)
    sheets = json.loads(SHEETS.read_text(encoding="utf-8"))["sheets"]
    started = time.perf_counter()
    converter = build_converter()
    print(f"OCR models loaded in {time.perf_counter() - started:.1f}s")

    records, misses = [], 0
    try:
        for sheet in sheets:
            build_copy(sheet)
            path = ROOT / sheet["image"]
            started = time.perf_counter()
            page = read_page(converter, path.read_bytes(), path.name)
            print(f"{sheet['id']}: {len(page.lines)} OCR lines in {time.perf_counter() - started:.1f}s ({page.width:.0f}x{page.height:.0f})")
            model = None
            mapping = truth_mapping(sheet, page)
            if use_gemini:
                mapping, model, usage = await map_fields(page, app)
                print(f"  {model}: {usage.prompt_token_count} input / {usage.candidates_token_count} output tokens")
            fields, warnings = build_fields(mapping, page)
            costs, cost_warnings = build_costs(mapping, page)
            warnings += cost_warnings
            checks = detect_checks(page, fields)
            misses += score(sheet, fields, costs)
            for warning in warnings:
                print(f"  warning [{warning['code']}] {warning['message']}")
            print(f"  checks: {', '.join(check['title'] for check in checks) or 'none'}")
            extracted_at = datetime.now(UTC).isoformat(timespec="milliseconds").replace("+00:00", "Z")
            reading = to_contract(
                fields,
                warnings,
                costs=costs,
                checks=checks,
                lines=contract_lines(page),
                document_id=None,
                extracted_at=extracted_at,
                model=model,
                ocr=OCR_ENGINE_LABEL,
                mode="recorded",
                image=ImageSize(width=round(page.width), height=round(page.height)),
            )
            confirmed = {key: sheet["fields"][key]["value"] for key in FIELD_KEYS}
            records.append({"id": sheet["id"], "image": Path(sheet["image"]).relative_to("web").as_posix(), "reading": reading, "confirmed": confirmed})
    finally:
        await app.state.close_gemini()

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(f"{HEADER}export const SHEETS = {json.dumps(records, ensure_ascii=False, indent=2)};\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}; {misses} field(s) differ from the ground truth")
    return 1 if use_gemini and misses else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--gemini", action="store_true", help="map fields with Gemini (billed) and score it against the ground truth")
    return asyncio.run(record(parser.parse_args().gemini))


if __name__ == "__main__":
    sys.exit(main())
