import { escapeHTML as e } from '../../helper.js';
import { sourceLink, safeLink, attribution, mapsCredit, formatTime } from '../../shared/maps.js';
import { reviewTopics } from './services.js';
export const markup=`<details class="feature-section" id="reviewsSection"><summary>建物の口コミと、自分の内見記録</summary><p>口コミは投稿者の報告です。住人かどうか、現在の部屋にも当てはまるかは分かりません。</p><label>確認する候補<select id="reviewCandidate"></select></label><div class="choice-row"><button class="button" id="reviewSearch">建物の地点を探す</button></div><p id="reviewStatus" role="status"></p><div id="reviewChoices"></div><div id="reviewResults"></div><form id="observationForm" class="feature-form"><label>内見した日<input type="date" name="date" required /></label><label>自分で確認したこと<textarea name="text" maxlength="1000" rows="3" required placeholder="例：平日19時、窓を閉めた状態で道路の音を確認"></textarea></label><button class="button">自分の記録として保存</button></form><div id="ownObservations"></div></details>`;
export function resultsMarkup(result){
  const topics=reviewTopics(result.reviews);
  return `<p>${mapsCredit} · ${sourceLink(result.place.url,result.place.name)} · ${e(formatTime(result.checkedAt))}取得 ${attribution(result.place.attributions)}</p><p class="section-hint">建物地点への投稿。住人であることは未確認。Googleの関連度順・最大5件で、全件や代表的な意見ではありません。${result.rating==null?'':`地点評価 ${result.rating} / 5（${result.count??'件数不明'}件）。住みやすさの点数には変換しません。`}</p>
    ${result.reviews.map((r,i)=>`<article class="review-entry" id="review-${i}"><div class="review-author">${safeLink(r.author.photo)?`<img src="${e(safeLink(r.author.photo))}" alt="${e(r.author.name)}" width="32" height="32" loading="lazy" referrerpolicy="no-referrer" />`:''}<strong>${sourceLink(r.author.url,r.author.name)||e(r.author.name)}</strong><span>${e(r.relativeTime||formatTime(r.publishedAt))} · ${r.rating??'評価未取得'}</span></div><p>${e(r.text)}</p>${r.originalText&&r.originalText!==r.text?`<details><summary>翻訳前の投稿を見る</summary><p>${e(r.originalText)}</p></details>`:''}<p>${sourceLink(r.url,'元の口コミ')} ${sourceLink(r.reportUrl,'問題を報告')}</p></article>`).join('')||'<p>表示できる口コミがありません。口コミがないことは問題がない証拠ではありません。</p>'}
    ${topics.length?`<div class="context-question"><h4>次の内見で、何を確かめますか？</h4><p>以下は語句による分類です。肯定・否定をまとめた結論ではありません。</p>${topics.map(t=>`<p>${t.label}：${t.indices.map(i=>`<a href="#review-${i}">投稿${i+1}</a>`).join('、')}</p><button class="button" data-review-topic="${t.key}">${t.question} を確認事項に加える</button>`).join('')}</div>`:''}`;
}
