import { escapeHTML as e, yen } from "../../helper.js";
import { sourceLink } from "../../shared/maps.js";
export function briefMarkup(brief) {
  return `<h2>${e(brief.title)}</h2><p>作成：${e(brief.generatedAt)} · 作成時点のメモ</p><h3>確認した希望</h3><pre>${e(brief.preferences)}</pre>${brief.destination ? `<h3>共有する目的地</h3><p>${e(brief.destination)}</p>` : ""}<h3>候補</h3>${brief.candidates.map((p) => `<article><h4>${e(p.name)}</h4><p>月額：${p.monthly == null ? "未確認" : yen(p.monthly)} · 面積：${p.area == null ? "未確認" : `${p.area}㎡`}</p>${p.sources.map((s) => `<p>${sourceLink(s.url, s.label)} ${e(s.retrievedAt)}</p>`).join("")}</article>`).join("")}<h3>次に確かめること</h3><ul>${brief.questions.map((q) => `<li>${e(q)}</li>`).join("")}</ul><p>参考価格・地図の経路・口コミ本文は含みません。掲載状況や費用は元の情報で再確認してください。</p>`;
}
export function exportHTML(brief, images = [], history = []) {
  const pictures = images.filter((i) =>
    /^data:image\/(png|jpeg|webp);base64,/.test(i.src),
  );
  return `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'"><title>Rental Helper — 条件メモ</title><style>body{font:15px/1.8 sans-serif;max-width:900px;margin:32px auto;padding:20px;color:#243b33}pre{white-space:pre-wrap;font:inherit}article{border-bottom:1px solid #ddd;padding:14px 0}img{max-width:100%;height:auto}a{color:#27634c}</style><body>${briefMarkup(brief)}${pictures.length ? `<h3>共有を選んだ画像</h3>${pictures.map((i) => `<figure><img src="${e(i.src)}" alt="${e(i.name)}"><figcaption>${e(i.name)}</figcaption></figure>`).join("")}` : ""}${history.length ? `<h3>共有を選んだ会話（AIの解釈を含む）</h3>${history.map((t) => `<p><strong>${t.role === "user" ? "あなた" : "AI"}</strong>：${e(t.text)}</p>`).join("")}` : ""}</body></html>`;
}
export const markup = `<section class="feature-section" id="sharingSection" aria-labelledby="sharingSectionTitle"><h3 id="sharingSectionTitle">共有内容のプレビュー</h3><p>確認した希望・候補の掲載値・次の確認事項を共有します。下で実際の内容を確認できます。</p><div class="share-options"><label><input type="checkbox" id="shareDestination"> 入力した目的地を含める</label><label><input type="checkbox" id="shareImages"> 画像を含める（HTMLファイルのみ）</label><label><input type="checkbox" id="shareConversation"> 会話を含める（HTMLのみ・地図を含む会話は不可）</label></div><p class="section-hint">地図の経路や口コミ本文は共有しません。自動生成されたメモは「条件メモ」タブからコピーできます。</p><div id="sharePreview" class="share-preview"></div><div id="shareExtras"></div><div class="choice-row"><button class="button" id="exportBrief">HTMLファイルを保存</button><label>リンクの期限<select id="shareDays"><option value="1">1日</option><option value="3">3日</option><option value="7">7日</option></select></label><button class="button" id="createShare">表示内容で共有リンクを作る</button></div><p class="section-hint">リンクを知る人は閲覧できます。期限切れ・削除後は閲覧できませんが、受取人が保存したコピーは削除できません。</p><p id="shareStatus" role="status"></p><div id="shareLinks"></div></section>`;
